# Generated by Django 4.1.5 on 2023-02-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
